name: Generate JSON

on:
  push:
    paths:
      - 'artikelen/articles/**.md'
      - 'preken/articles/**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ensure LF line endings
        run: |
          git config --global core.autocrlf input

      - name: Generate artikelen/posts.json
        run: |
          mkdir -p artikelen
          jq -n '
            [inputs]
          ' > artikelen/posts.json < <(
            for file in artikelen/articles/*.md; do
              title=$(grep '^title:' "$file" | sed 's/title: //' | tr -d '\r')
              date=$(grep '^date:' "$file" | sed 's/date: //' | tr -d '\r')
              description=$(grep '^description:' "$file" | sed 's/description: //' | tr -d '\r')
              filename=$(basename "$file" .md)
      
              jq -n \
                --arg title "$title" \
                --arg file "$filename" \
                --arg date "$date" \
                --arg description "$description" \
                '{title:$title,file:$file,date:$date,description:$description}'
            done
          )

      - name: Generate preken/posts.json
        run: |
          mkdir -p preken
          jq -n '
            [inputs]
          ' > preken/posts.json < <(
            for file in preken/articles/*.md; do
              title=$(grep '^title:' "$file" | sed 's/title: //' | tr -d '\r')
              date=$(grep '^date:' "$file" | sed 's/date: //' | tr -d '\r')
              description=$(grep '^description:' "$file" | sed 's/description: //' | tr -d '\r')
              filename=$(basename "$file" .md)
      
              jq -n \
                --arg title "$title" \
                --arg file "$filename" \
                --arg date "$date" \
                --arg description "$description" \
                '{title:$title,file:$file,date:$date,description:$description}'
            done
          )

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git add artikelen/posts.json preken/posts.json
          git commit -m "Auto update artikelen/posts.json & preken/posts.json" || echo "No changes"
          git push
